hide_window_decorations titlebar-only 
window_padding_width 10 0

foreground #f2f2f2
background #1e2430
background_opacity 0.85
background_blur 16

cursor_trail 3
cursor_trail_decay 0.1 0.3

font_size 14.0
